### ISSUE TITLE
Schema Tool can't load descriptions and set optional fields to be required

### ISSUE THREAD

**Issue by ChunyiLyu** [knative/hack#155]
I've tried following instruction using the [schema tool](https://github.com/knative/hack/tree/main/schema) to generate CRD for rabbitmqsources in [eventing-rabbitmq](github.com/knative-sandbox/eventing-rabbitmq).

If you run `go run ./ dump RabbitmqSource`, the output crd looks like:
```
type: object
properties:
  spec:
    description: 'not found: unable to parse dir: error parse dir "./pkg/apis/sources/v1alpha1": open ./pkg/apis/sources/v1alpha1: no such file or directory'
    type: object
    required:
      - sink
    properties:
      brokers:
        description: 'not found: unable to parse dir: error parse dir "./pkg/apis/sources/v1alpha1": open ./pkg/apis/sources/v1alpha1: no such file or directory'
        type: string
      channel_config:
        description: 'not found: unable to parse dir: error parse dir "./pkg/apis/sources/v1alpha1": open ./pkg/apis/sources/v1alpha1: no such file or directory'
        type: object
        required:
          - prefetch_count
        ...
      observedGeneration:
        description: 'not found: unable to parse dir: error parse dir "vendor/knative.dev/pkg/apis/duck/v1": open vendor/knative.dev/pkg/apis/duck/v1: no such file or directory'
        type: integer
        format: int64
      sinkUri:
        description: 'not found: unable to parse dir: error parse dir "vendor/knative.dev/pkg/apis/duck/v1": open vendor/knative.dev/pkg/apis/duck/v1: no such file or directory'
        type: string
```

It can't find fields descriptions and set some optional fields to be required instead. 
Used [fork](https://github.com/ChunyiLyu/eventing-rabbitmq/tree/rabbitmqsources-crd-schema)
