### ISSUE TITLE
schema tool doesn't support well for array item

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/hack#59]
when generate CRDs for array items,is is as follows:

```yaml
instances:
    description: Instances specifies multi revisions you can release at one time.
    type: array
    items:
      type: object
```

which will be  ignored by kubernetes see [k8s doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#rawextension), it should be like this 

```yaml
instances:
      description: Instances specifies multi revisions you can release at one time.
      type: array
      items:
        type: object
        x-kubernetes-preserve-unknown-fields: true
```
